### ISSUE TITLE
Add rl_usbd_lib.h back into Components/USB/Include/

### ISSUE THREAD

**Issue by mhjartstrom** [ARM-software/MDK-Middleware#42]
In SHA 623e3cc15530895148f776b916f962f25188ed28 the rl_usbd_lib.h header file was moved into Components/USB/Source/usbd_lib.h, leaving us who use the structures defined within with a dysfunctional Pack when building this into a release. Why? Please add it back using the regular name.

**Comment by MiloradCvjetkovic** [comment]
Which structures from rl_usbd_lib.h are you using @mhjartstrom ?

**Comment by mhjartstrom** [comment]
We use usbd_desc_t to be able to parse and modify usbd0_desc and usbd1_desc.
