### ISSUE TITLE
Rework Examples documentation and README.md for examples

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/MDK-Middleware#45]
The examples documentation needs work.

We should create a top-level documentation on how examples are used.

For USB we do not provide the scope of examples that is currently explained here
https://arm-software.github.io/MDK-Middleware/latest/USB/USB_Device.html#USB_Device_Tutorial

The README.md files need rework.  A potential way is in https://github.com/ARM-software/MDK-Middleware/pull/44

**Comment by RobertRostohar** [comment]
Example documentation has been reworked (see #56).
