### ISSUE TITLE
Suggest to add "Working with Examples"

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/MDK-Middleware#46]
Suggest to add an section "Working with Examples" below: 
 - https://arm-software.github.io/MDK-Middleware/latest/General/index.html

Sections:

## Using VS Code
This section explains how to use MDK-Middleware with the [Arm CMSIS Solution](https://marketplace.visualstudio.com/items?itemName=Arm.cmsis-csolution) for VS Code. This extension is for example part of [Keil Studio](https://www.keil.arm.com/).

### Use uVision Debugger
This section shows how to call the uVision Debugger from VS Code and use the advanced debug features such as Event Recorder and Component Viewer to analyse the MDK-Middleware.

### Use VS Code Debugger
This section shows how to use VS Code Debug Extensions to analyse the MDK-Middleware.

## Using uVision IDE
This section explains how to create applications using the uVision IDE.

**Comment by RobertRostohar** [comment]
Done in #65.
